### ISSUE TITLE
Test suite missing files on Hackage

### ISSUE THREAD

**Issue by snoyberg** [myfreeweb/microformats2-parser#3]
```
Preprocessing test suite 'tests' for microformats2-parser-1.0.1...

test-suite/Data/Microformats2/ParserSpec.hs:7:18:
    Could not find module ‘TestCommon’
    Perhaps you meant Heist.Common
    Use -v to see a list of the files searched for.
```

**Comment by myfreeweb** [comment]
Should be fine in 1.0.1.1.

By the way, does `stack` ignore the file list in the `.cabal` file? Tests somehow work with `stack test` without specifying the modules in `other-modules`...

**Comment by snoyberg** [comment]
This is an old Cabal annoyance: the test suites will work locally, but not from Hackage, because sdist won't include it. stack is just using Cabal for building, so it gets this annoyance too. However, recent versions of stack (since 0.1.3.0) should give you a warning when you use a module which isn't listed in your cabal file.
